// 200+ MCQs for the Class Quiz Competition. Each: [question, [3 options], correctIndex]
export type QuizQ = { q: string; opts: [string, string, string]; a: 0 | 1 | 2; cat?: string };

export const QUIZ_BANK: QuizQ[] = [
  // ===== General Knowledge (India) =====
  { q: "Who is known as the Father of the Nation in India?", opts: ["Jawaharlal Nehru", "Mahatma Gandhi", "B. R. Ambedkar"], a: 1, cat: "GK" },
  { q: "The capital of India is:", opts: ["Mumbai", "Kolkata", "New Delhi"], a: 2, cat: "GK" },
  { q: "Which is the national bird of India?", opts: ["Peacock", "Parrot", "Eagle"], a: 0, cat: "GK" },
  { q: "Which is the national animal of India?", opts: ["Lion", "Tiger", "Elephant"], a: 1, cat: "GK" },
  { q: "Which river is called the 'Ganga of the South'?", opts: ["Krishna", "Godavari", "Kaveri"], a: 1, cat: "GK" },
  { q: "The 'Land of Five Rivers' is:", opts: ["Haryana", "Punjab", "Kerala"], a: 1, cat: "GK" },
  { q: "Who wrote the Indian National Anthem?", opts: ["Rabindranath Tagore", "Bankim Chandra", "Sarojini Naidu"], a: 0, cat: "GK" },
  { q: "Who wrote 'Vande Mataram'?", opts: ["Tagore", "Bankim Chandra Chattopadhyay", "Sri Aurobindo"], a: 1, cat: "GK" },
  { q: "The Indian Constitution came into force on:", opts: ["15 August 1947", "26 January 1950", "2 October 1950"], a: 1, cat: "GK" },
  { q: "Who was the first President of India?", opts: ["Dr. Rajendra Prasad", "Dr. S. Radhakrishnan", "Zakir Hussain"], a: 0, cat: "GK" },
  { q: "The longest river in India is:", opts: ["Yamuna", "Ganga", "Brahmaputra"], a: 1, cat: "GK" },
  { q: "The largest state in India by area is:", opts: ["Madhya Pradesh", "Rajasthan", "Uttar Pradesh"], a: 1, cat: "GK" },
  { q: "The smallest state in India by area is:", opts: ["Goa", "Sikkim", "Tripura"], a: 0, cat: "GK" },
  { q: "The Taj Mahal was built by:", opts: ["Akbar", "Shah Jahan", "Aurangzeb"], a: 1, cat: "GK" },
  { q: "The Taj Mahal is located in:", opts: ["Delhi", "Agra", "Jaipur"], a: 1, cat: "GK" },
  { q: "'Jai Hind' was popularised by:", opts: ["Bhagat Singh", "Subhas Chandra Bose", "Nehru"], a: 1, cat: "GK" },
  { q: "Which is the highest civilian award in India?", opts: ["Padma Vibhushan", "Bharat Ratna", "Padma Shri"], a: 1, cat: "GK" },
  { q: "The national flower of India is:", opts: ["Rose", "Lotus", "Sunflower"], a: 1, cat: "GK" },
  { q: "The national fruit of India is:", opts: ["Apple", "Banana", "Mango"], a: 2, cat: "GK" },
  { q: "The national tree of India is:", opts: ["Banyan", "Neem", "Peepal"], a: 0, cat: "GK" },
  { q: "'Discovery of India' was written by:", opts: ["Gandhi", "Nehru", "Ambedkar"], a: 1, cat: "GK" },
  { q: "The Jallianwala Bagh massacre happened in:", opts: ["1919", "1920", "1930"], a: 0, cat: "GK" },
  { q: "India got independence in:", opts: ["1945", "1947", "1950"], a: 1, cat: "GK" },
  { q: "First woman Prime Minister of India:", opts: ["Sonia Gandhi", "Indira Gandhi", "Pratibha Patil"], a: 1, cat: "GK" },
  { q: "First Indian to go to space:", opts: ["Rakesh Sharma", "Kalpana Chawla", "Sunita Williams"], a: 0, cat: "GK" },

  // ===== Science =====
  { q: "H2O is the chemical formula for:", opts: ["Salt", "Water", "Oxygen"], a: 1, cat: "Science" },
  { q: "The gas we breathe in is:", opts: ["Carbon Dioxide", "Oxygen", "Nitrogen"], a: 1, cat: "Science" },
  { q: "The gas plants use for photosynthesis is:", opts: ["Oxygen", "Nitrogen", "Carbon Dioxide"], a: 2, cat: "Science" },
  { q: "The powerhouse of the cell is:", opts: ["Nucleus", "Mitochondria", "Ribosome"], a: 1, cat: "Science" },
  { q: "How many bones are in an adult human body?", opts: ["206", "212", "198"], a: 0, cat: "Science" },
  { q: "The largest organ in the human body is:", opts: ["Liver", "Skin", "Brain"], a: 1, cat: "Science" },
  { q: "Which planet is known as the Red Planet?", opts: ["Venus", "Mars", "Jupiter"], a: 1, cat: "Science" },
  { q: "The largest planet in our solar system is:", opts: ["Saturn", "Jupiter", "Neptune"], a: 1, cat: "Science" },
  { q: "The smallest planet in our solar system is:", opts: ["Mercury", "Mars", "Venus"], a: 0, cat: "Science" },
  { q: "How many planets are there in our solar system?", opts: ["7", "8", "9"], a: 1, cat: "Science" },
  { q: "The Sun is a:", opts: ["Planet", "Star", "Comet"], a: 1, cat: "Science" },
  { q: "Speed of light is approximately:", opts: ["3×10⁸ m/s", "3×10⁶ m/s", "3×10¹⁰ m/s"], a: 0, cat: "Science" },
  { q: "Water boils at:", opts: ["90°C", "100°C", "120°C"], a: 1, cat: "Science" },
  { q: "Water freezes at:", opts: ["0°C", "-10°C", "10°C"], a: 0, cat: "Science" },
  { q: "The chemical symbol for gold is:", opts: ["Go", "Au", "Ag"], a: 1, cat: "Science" },
  { q: "The chemical symbol for silver is:", opts: ["Si", "Ag", "Sv"], a: 1, cat: "Science" },
  { q: "The hardest natural substance is:", opts: ["Iron", "Diamond", "Quartz"], a: 1, cat: "Science" },
  { q: "Sound cannot travel through:", opts: ["Water", "Air", "Vacuum"], a: 2, cat: "Science" },
  { q: "The unit of electric current is:", opts: ["Volt", "Ampere", "Ohm"], a: 1, cat: "Science" },
  { q: "Newton is the SI unit of:", opts: ["Energy", "Force", "Power"], a: 1, cat: "Science" },
  { q: "Who invented the telephone?", opts: ["Edison", "Bell", "Tesla"], a: 1, cat: "Science" },
  { q: "Who invented the light bulb?", opts: ["Edison", "Newton", "Faraday"], a: 0, cat: "Science" },
  { q: "Who proposed the theory of relativity?", opts: ["Newton", "Einstein", "Hawking"], a: 1, cat: "Science" },
  { q: "Who discovered gravity?", opts: ["Galileo", "Newton", "Einstein"], a: 1, cat: "Science" },
  { q: "The study of living things is:", opts: ["Physics", "Biology", "Chemistry"], a: 1, cat: "Science" },
  { q: "The study of stars and planets is:", opts: ["Geology", "Astronomy", "Biology"], a: 1, cat: "Science" },
  { q: "Photosynthesis takes place in the:", opts: ["Roots", "Leaves", "Stem"], a: 1, cat: "Science" },
  { q: "How many chambers does the human heart have?", opts: ["2", "3", "4"], a: 2, cat: "Science" },
  { q: "Red blood cells carry:", opts: ["Nutrients", "Oxygen", "Hormones"], a: 1, cat: "Science" },
  { q: "The blood pumping organ is:", opts: ["Lung", "Liver", "Heart"], a: 2, cat: "Science" },
  { q: "Sound travels fastest in:", opts: ["Air", "Water", "Solid"], a: 2, cat: "Science" },
  { q: "Rainbow has how many colours?", opts: ["5", "6", "7"], a: 2, cat: "Science" },
  { q: "Blood is red because of:", opts: ["Iron", "Copper", "Zinc"], a: 0, cat: "Science" },
  { q: "The pH of pure water is:", opts: ["6", "7", "8"], a: 1, cat: "Science" },
  { q: "Which vitamin is produced from sunlight?", opts: ["Vitamin A", "Vitamin C", "Vitamin D"], a: 2, cat: "Science" },
  { q: "Malaria is caused by:", opts: ["Virus", "Bacteria", "Parasite"], a: 2, cat: "Science" },
  { q: "The largest desert in the world is:", opts: ["Sahara", "Gobi", "Antarctica"], a: 2, cat: "Science" },
  { q: "The ozone layer protects us from:", opts: ["Cosmic rays", "UV rays", "Infrared rays"], a: 1, cat: "Science" },
  { q: "How many teeth does an adult human have?", opts: ["28", "30", "32"], a: 2, cat: "Science" },
  { q: "The centre of an atom is called:", opts: ["Electron", "Nucleus", "Proton"], a: 1, cat: "Science" },

  // ===== Math =====
  { q: "What is 12 × 12?", opts: ["124", "144", "154"], a: 1, cat: "Math" },
  { q: "What is 15 × 8?", opts: ["120", "125", "115"], a: 0, cat: "Math" },
  { q: "The square root of 144 is:", opts: ["10", "12", "14"], a: 1, cat: "Math" },
  { q: "The square root of 169 is:", opts: ["11", "12", "13"], a: 2, cat: "Math" },
  { q: "What is 25% of 200?", opts: ["25", "50", "75"], a: 1, cat: "Math" },
  { q: "What is 10% of 500?", opts: ["25", "50", "100"], a: 1, cat: "Math" },
  { q: "Pi (π) is approximately:", opts: ["3.14", "2.72", "1.61"], a: 0, cat: "Math" },
  { q: "The number of sides in a hexagon is:", opts: ["5", "6", "7"], a: 1, cat: "Math" },
  { q: "The sum of angles in a triangle is:", opts: ["90°", "180°", "360°"], a: 1, cat: "Math" },
  { q: "The sum of angles in a quadrilateral is:", opts: ["180°", "270°", "360°"], a: 2, cat: "Math" },
  { q: "How many degrees are in a right angle?", opts: ["45°", "90°", "180°"], a: 1, cat: "Math" },
  { q: "A polygon with 8 sides is a:", opts: ["Hexagon", "Octagon", "Pentagon"], a: 1, cat: "Math" },
  { q: "A polygon with 5 sides is a:", opts: ["Pentagon", "Hexagon", "Heptagon"], a: 0, cat: "Math" },
  { q: "The area of a circle formula is:", opts: ["2πr", "πr²", "πd"], a: 1, cat: "Math" },
  { q: "The perimeter of a rectangle formula is:", opts: ["l×b", "2(l+b)", "l+b"], a: 1, cat: "Math" },
  { q: "0! (zero factorial) equals:", opts: ["0", "1", "undefined"], a: 1, cat: "Math" },
  { q: "The smallest prime number is:", opts: ["1", "2", "3"], a: 1, cat: "Math" },
  { q: "Is 1 a prime number?", opts: ["Yes", "No", "Sometimes"], a: 1, cat: "Math" },
  { q: "The value of 2^10 is:", opts: ["512", "1024", "2048"], a: 1, cat: "Math" },
  { q: "The LCM of 4 and 6 is:", opts: ["10", "12", "24"], a: 1, cat: "Math" },
  { q: "The HCF of 12 and 18 is:", opts: ["4", "6", "9"], a: 1, cat: "Math" },
  { q: "1 km = ? metres", opts: ["100", "1000", "10000"], a: 1, cat: "Math" },
  { q: "1 kg = ? grams", opts: ["100", "1000", "10000"], a: 1, cat: "Math" },
  { q: "1 hour = ? seconds", opts: ["360", "3600", "6000"], a: 1, cat: "Math" },
  { q: "The number 0 is:", opts: ["Positive", "Negative", "Neither"], a: 2, cat: "Math" },

  // ===== Geography =====
  { q: "Which is the largest ocean in the world?", opts: ["Atlantic", "Pacific", "Indian"], a: 1, cat: "Geo" },
  { q: "Mount Everest is located in:", opts: ["India", "Nepal", "China"], a: 1, cat: "Geo" },
  { q: "The largest continent is:", opts: ["Africa", "Asia", "Europe"], a: 1, cat: "Geo" },
  { q: "The smallest continent is:", opts: ["Europe", "Antarctica", "Australia"], a: 2, cat: "Geo" },
  { q: "The longest river in the world is:", opts: ["Amazon", "Nile", "Yangtze"], a: 1, cat: "Geo" },
  { q: "The capital of France is:", opts: ["Rome", "Paris", "Madrid"], a: 1, cat: "Geo" },
  { q: "The capital of Japan is:", opts: ["Beijing", "Seoul", "Tokyo"], a: 2, cat: "Geo" },
  { q: "The capital of Australia is:", opts: ["Sydney", "Canberra", "Melbourne"], a: 1, cat: "Geo" },
  { q: "The capital of the USA is:", opts: ["New York", "Washington D.C.", "Los Angeles"], a: 1, cat: "Geo" },
  { q: "The capital of the UK is:", opts: ["London", "Manchester", "Liverpool"], a: 0, cat: "Geo" },
  { q: "The Great Wall is in:", opts: ["Japan", "China", "India"], a: 1, cat: "Geo" },
  { q: "Eiffel Tower is in:", opts: ["London", "Paris", "Berlin"], a: 1, cat: "Geo" },
  { q: "Which country has the most population?", opts: ["USA", "India", "China"], a: 1, cat: "Geo" },
  { q: "The Sahara Desert is in:", opts: ["Asia", "Africa", "Australia"], a: 1, cat: "Geo" },
  { q: "The Amazon rainforest is mostly in:", opts: ["Africa", "Brazil", "India"], a: 1, cat: "Geo" },
  { q: "Kolkata is on the banks of which river?", opts: ["Ganga", "Hooghly", "Yamuna"], a: 1, cat: "Geo" },
  { q: "The Deccan Plateau is in:", opts: ["North India", "South India", "East India"], a: 1, cat: "Geo" },
  { q: "Which state is called 'God's own country'?", opts: ["Goa", "Kerala", "Karnataka"], a: 1, cat: "Geo" },
  { q: "The Thar Desert is in:", opts: ["Gujarat", "Rajasthan", "Maharashtra"], a: 1, cat: "Geo" },
  { q: "Which is the coldest continent?", opts: ["Antarctica", "Europe", "Asia"], a: 0, cat: "Geo" },
  { q: "The equator passes through how many continents?", opts: ["2", "3", "4"], a: 1, cat: "Geo" },
  { q: "Which country is known as the Land of the Rising Sun?", opts: ["China", "Japan", "Korea"], a: 1, cat: "Geo" },
  { q: "Which is the highest mountain in the world?", opts: ["K2", "Mount Everest", "Kanchenjunga"], a: 1, cat: "Geo" },
  { q: "Currency of Japan is:", opts: ["Yuan", "Yen", "Won"], a: 1, cat: "Geo" },
  { q: "Currency of USA is:", opts: ["Pound", "Dollar", "Euro"], a: 1, cat: "Geo" },

  // ===== History =====
  { q: "The First War of Indian Independence took place in:", opts: ["1857", "1919", "1942"], a: 0, cat: "History" },
  { q: "The Quit India Movement was launched in:", opts: ["1930", "1942", "1947"], a: 1, cat: "History" },
  { q: "Dandi March (Salt March) was led by:", opts: ["Nehru", "Gandhi", "Bose"], a: 1, cat: "History" },
  { q: "The Battle of Plassey was fought in:", opts: ["1757", "1857", "1707"], a: 0, cat: "History" },
  { q: "Who founded the Mughal Empire?", opts: ["Akbar", "Babur", "Humayun"], a: 1, cat: "History" },
  { q: "Ashoka belonged to which dynasty?", opts: ["Gupta", "Maurya", "Chola"], a: 1, cat: "History" },
  { q: "The Golden Age of India was during:", opts: ["Maurya period", "Gupta period", "Mughal period"], a: 1, cat: "History" },
  { q: "Chandragupta Maurya was guided by:", opts: ["Kautilya", "Kalidasa", "Aryabhatta"], a: 0, cat: "History" },
  { q: "Who was the first Governor-General of independent India?", opts: ["Mountbatten", "C. Rajagopalachari", "Nehru"], a: 0, cat: "History" },
  { q: "Where was Mahatma Gandhi born?", opts: ["Rajkot", "Porbandar", "Ahmedabad"], a: 1, cat: "History" },
  { q: "Bhagat Singh was executed in:", opts: ["1929", "1931", "1935"], a: 1, cat: "History" },
  { q: "Who founded the Indian National Congress?", opts: ["A.O. Hume", "Gandhi", "Tilak"], a: 0, cat: "History" },
  { q: "The Non-Cooperation Movement was launched by:", opts: ["Nehru", "Gandhi", "Bose"], a: 1, cat: "History" },
  { q: "Who was the last Mughal emperor?", opts: ["Aurangzeb", "Shah Jahan", "Bahadur Shah II"], a: 2, cat: "History" },
  { q: "The Second World War ended in:", opts: ["1943", "1945", "1947"], a: 1, cat: "History" },
  { q: "Rani Lakshmibai was the queen of:", opts: ["Rajasthan", "Jhansi", "Mysore"], a: 1, cat: "History" },
  { q: "Who wrote 'Arthashastra'?", opts: ["Kalidasa", "Chanakya (Kautilya)", "Aryabhatta"], a: 1, cat: "History" },
  { q: "The Harappan Civilization is also known as:", opts: ["Vedic", "Indus Valley", "Aryan"], a: 1, cat: "History" },
  { q: "Buddha attained enlightenment at:", opts: ["Lumbini", "Bodh Gaya", "Sarnath"], a: 1, cat: "History" },
  { q: "Where was Buddha born?", opts: ["Bodh Gaya", "Lumbini", "Kapilavastu"], a: 1, cat: "History" },

  // ===== English / Grammar =====
  { q: "Plural of 'child' is:", opts: ["Childs", "Childrens", "Children"], a: 2, cat: "English" },
  { q: "Plural of 'mouse' is:", opts: ["Mouses", "Mice", "Mices"], a: 1, cat: "English" },
  { q: "Plural of 'foot' is:", opts: ["Foots", "Feet", "Feets"], a: 1, cat: "English" },
  { q: "Opposite of 'brave' is:", opts: ["Bold", "Coward", "Strong"], a: 1, cat: "English" },
  { q: "Opposite of 'ancient' is:", opts: ["Modern", "Old", "Historic"], a: 0, cat: "English" },
  { q: "Synonym of 'happy' is:", opts: ["Sad", "Joyful", "Angry"], a: 1, cat: "English" },
  { q: "Synonym of 'beautiful' is:", opts: ["Ugly", "Gorgeous", "Plain"], a: 1, cat: "English" },
  { q: "A word used to describe a noun is:", opts: ["Verb", "Adjective", "Adverb"], a: 1, cat: "English" },
  { q: "A word that shows action is a:", opts: ["Noun", "Verb", "Pronoun"], a: 1, cat: "English" },
  { q: "Past tense of 'go' is:", opts: ["Goed", "Went", "Gone"], a: 1, cat: "English" },
  { q: "Past tense of 'eat' is:", opts: ["Ate", "Eated", "Eaten"], a: 0, cat: "English" },
  { q: "Past tense of 'run' is:", opts: ["Runned", "Ran", "Run"], a: 1, cat: "English" },
  { q: "'He ___ playing football.' Fill in the blank:", opts: ["is", "are", "am"], a: 0, cat: "English" },
  { q: "'They ___ students.' Fill in the blank:", opts: ["is", "are", "am"], a: 1, cat: "English" },
  { q: "Which is a noun?", opts: ["Quickly", "Book", "Bright"], a: 1, cat: "English" },
  { q: "Article used before 'hour' is:", opts: ["a", "an", "the"], a: 1, cat: "English" },
  { q: "Article used before 'university' is:", opts: ["a", "an", "the"], a: 0, cat: "English" },
  { q: "Who wrote 'Romeo and Juliet'?", opts: ["Shakespeare", "Dickens", "Milton"], a: 0, cat: "English" },
  { q: "Who wrote 'The Jungle Book'?", opts: ["Kipling", "Twain", "Wilde"], a: 0, cat: "English" },
  { q: "Who wrote 'Harry Potter'?", opts: ["J.K. Rowling", "R.L. Stine", "Roald Dahl"], a: 0, cat: "English" },

  // ===== Sports =====
  { q: "The national sport of India is officially:", opts: ["Cricket", "Hockey (traditionally)", "Kabaddi"], a: 1, cat: "Sports" },
  { q: "Cricket originated in:", opts: ["England", "India", "Australia"], a: 0, cat: "Sports" },
  { q: "How many players in a football team?", opts: ["10", "11", "12"], a: 1, cat: "Sports" },
  { q: "How many players in a cricket team?", opts: ["10", "11", "12"], a: 1, cat: "Sports" },
  { q: "Who is called the 'Master Blaster'?", opts: ["Kohli", "Sachin Tendulkar", "Dhoni"], a: 1, cat: "Sports" },
  { q: "Wimbledon is associated with:", opts: ["Football", "Tennis", "Cricket"], a: 1, cat: "Sports" },
  { q: "'Bull's Eye' term is used in:", opts: ["Archery", "Football", "Golf"], a: 0, cat: "Sports" },
  { q: "The Olympics are held every:", opts: ["2 years", "4 years", "5 years"], a: 1, cat: "Sports" },
  { q: "Sachin Tendulkar's nickname is:", opts: ["Master Blaster", "Wall", "Captain Cool"], a: 0, cat: "Sports" },
  { q: "Rahul Dravid is nicknamed:", opts: ["Wall", "Wizard", "Warrior"], a: 0, cat: "Sports" },
  { q: "IPL stands for:", opts: ["Indian Premier League", "International Premier League", "Indian Play League"], a: 0, cat: "Sports" },
  { q: "The FIFA World Cup is held every:", opts: ["3 years", "4 years", "5 years"], a: 1, cat: "Sports" },
  { q: "Who won FIFA World Cup 2022?", opts: ["France", "Argentina", "Brazil"], a: 1, cat: "Sports" },
  { q: "Who won IPL 2025?", opts: ["CSK", "MI", "RCB"], a: 2, cat: "Sports" },
  { q: "MS Dhoni is nicknamed:", opts: ["Captain Cool", "Master", "King"], a: 0, cat: "Sports" },
  { q: "Which sport uses a shuttlecock?", opts: ["Tennis", "Badminton", "Squash"], a: 1, cat: "Sports" },

  // ===== Technology / Computers =====
  { q: "The full form of CPU is:", opts: ["Central Processing Unit", "Computer Personal Unit", "Central Program Unit"], a: 0, cat: "Tech" },
  { q: "The full form of RAM is:", opts: ["Read Access Memory", "Random Access Memory", "Rapid Access Memory"], a: 1, cat: "Tech" },
  { q: "The full form of WWW is:", opts: ["World Wide Web", "Web Wide World", "World Web Wide"], a: 0, cat: "Tech" },
  { q: "HTML stands for:", opts: ["Hyper Text Markup Language", "High Text Machine Language", "Home Tool Markup Language"], a: 0, cat: "Tech" },
  { q: "Who founded Microsoft?", opts: ["Steve Jobs", "Bill Gates", "Mark Zuckerberg"], a: 1, cat: "Tech" },
  { q: "Who founded Apple?", opts: ["Steve Jobs", "Bill Gates", "Elon Musk"], a: 0, cat: "Tech" },
  { q: "Who founded Facebook?", opts: ["Zuckerberg", "Musk", "Gates"], a: 0, cat: "Tech" },
  { q: "Who owns Tesla and SpaceX?", opts: ["Bezos", "Musk", "Zuckerberg"], a: 1, cat: "Tech" },
  { q: "Google was founded in:", opts: ["1995", "1998", "2001"], a: 1, cat: "Tech" },
  { q: "The 'brain' of a computer is:", opts: ["RAM", "Hard Disk", "CPU"], a: 2, cat: "Tech" },
  { q: "1 byte = ? bits", opts: ["4", "8", "16"], a: 1, cat: "Tech" },
  { q: "1 KB = ? bytes", opts: ["1024", "1000", "512"], a: 0, cat: "Tech" },
  { q: "The father of computers is:", opts: ["Charles Babbage", "Alan Turing", "Bill Gates"], a: 0, cat: "Tech" },
  { q: "'AI' stands for:", opts: ["Auto Internet", "Artificial Intelligence", "Advanced Interface"], a: 1, cat: "Tech" },
  { q: "Which company makes Android?", opts: ["Apple", "Microsoft", "Google"], a: 2, cat: "Tech" },
  { q: "Which company makes iOS?", opts: ["Google", "Apple", "Samsung"], a: 1, cat: "Tech" },
  { q: "PDF stands for:", opts: ["Portable Document Format", "Public Digital File", "Print Document File"], a: 0, cat: "Tech" },
  { q: "USB stands for:", opts: ["Universal Serial Bus", "United Serial Bus", "Uniform Signal Bus"], a: 0, cat: "Tech" },

  // ===== Fun / Misc =====
  { q: "How many colours are in the Indian flag?", opts: ["2", "3", "4"], a: 1, cat: "Fun" },
  { q: "The centre of the Indian flag has:", opts: ["Star", "Ashoka Chakra", "Sun"], a: 1, cat: "Fun" },
  { q: "How many spokes are in the Ashoka Chakra?", opts: ["22", "24", "26"], a: 1, cat: "Fun" },
  { q: "How many continents are there?", opts: ["5", "6", "7"], a: 2, cat: "Fun" },
  { q: "How many oceans are there?", opts: ["4", "5", "6"], a: 1, cat: "Fun" },
  { q: "A group of lions is called a:", opts: ["Pack", "Pride", "Herd"], a: 1, cat: "Fun" },
  { q: "Baby of a dog is called:", opts: ["Kitten", "Puppy", "Calf"], a: 1, cat: "Fun" },
  { q: "Baby of a cat is called:", opts: ["Puppy", "Kitten", "Cub"], a: 1, cat: "Fun" },
  { q: "Which animal is the tallest?", opts: ["Elephant", "Giraffe", "Horse"], a: 1, cat: "Fun" },
  { q: "Which is the fastest land animal?", opts: ["Lion", "Cheetah", "Horse"], a: 1, cat: "Fun" },
  { q: "Which is the largest animal in the world?", opts: ["Elephant", "Blue Whale", "Shark"], a: 1, cat: "Fun" },
  { q: "How many days are in a leap year?", opts: ["365", "366", "364"], a: 1, cat: "Fun" },
  { q: "How many months have 31 days?", opts: ["5", "6", "7"], a: 2, cat: "Fun" },
  { q: "Which is the first day of the week (traditional)?", opts: ["Monday", "Sunday", "Saturday"], a: 1, cat: "Fun" },
  { q: "How many primary colours are there?", opts: ["3", "5", "7"], a: 0, cat: "Fun" },
  { q: "Red + Yellow = ?", opts: ["Green", "Orange", "Purple"], a: 1, cat: "Fun" },
  { q: "Blue + Yellow = ?", opts: ["Green", "Purple", "Orange"], a: 0, cat: "Fun" },
  { q: "Red + Blue = ?", opts: ["Green", "Purple", "Orange"], a: 1, cat: "Fun" },
  { q: "Diwali is the festival of:", opts: ["Colours", "Lights", "Harvest"], a: 1, cat: "Fun" },
  { q: "Holi is the festival of:", opts: ["Lights", "Colours", "Food"], a: 1, cat: "Fun" },
  { q: "Which festival celebrates the birth of Lord Krishna?", opts: ["Janmashtami", "Diwali", "Holi"], a: 0, cat: "Fun" },
  { q: "Christmas is celebrated on:", opts: ["24 Dec", "25 Dec", "31 Dec"], a: 1, cat: "Fun" },
  { q: "Independence Day of India is on:", opts: ["15 August", "26 January", "2 October"], a: 0, cat: "Fun" },
  { q: "Republic Day of India is on:", opts: ["15 August", "26 January", "2 October"], a: 1, cat: "Fun" },
  { q: "Gandhi Jayanti is on:", opts: ["15 August", "26 January", "2 October"], a: 2, cat: "Fun" },
  { q: "Teacher's Day in India is on:", opts: ["5 September", "5 October", "14 November"], a: 0, cat: "Fun" },
  { q: "Children's Day in India is on:", opts: ["14 November", "5 September", "1 June"], a: 0, cat: "Fun" },
  { q: "Which colour is at the top of the Indian flag?", opts: ["Green", "White", "Saffron"], a: 2, cat: "Fun" },
  { q: "Which colour is at the bottom of the Indian flag?", opts: ["Green", "White", "Saffron"], a: 0, cat: "Fun" },
  { q: "How many strings does a guitar usually have?", opts: ["4", "6", "8"], a: 1, cat: "Fun" },
  { q: "The tabla is a type of:", opts: ["String instrument", "Drum", "Wind instrument"], a: 1, cat: "Fun" },
  { q: "The sitar was popularised worldwide by:", opts: ["Zakir Hussain", "Ravi Shankar", "A. R. Rahman"], a: 1, cat: "Fun" },
  { q: "Which Indian composer won an Oscar for 'Jai Ho'?", opts: ["A.R. Rahman", "Shankar", "Ilayaraja"], a: 0, cat: "Fun" },
  { q: "How many vowels are in the English alphabet?", opts: ["5", "6", "7"], a: 0, cat: "Fun" },
  { q: "How many letters are in the English alphabet?", opts: ["24", "25", "26"], a: 2, cat: "Fun" },
  { q: "Emoji '🎉' means:", opts: ["Anger", "Celebration", "Sadness"], a: 1, cat: "Fun" },
  { q: "The colour of chlorophyll is:", opts: ["Red", "Green", "Blue"], a: 1, cat: "Fun" },
  { q: "What do bees produce?", opts: ["Milk", "Honey", "Silk"], a: 1, cat: "Fun" },
  { q: "Which insect produces silk?", opts: ["Bee", "Silkworm", "Butterfly"], a: 1, cat: "Fun" },
  { q: "What is the tallest building in the world (2024)?", opts: ["Burj Khalifa", "Shanghai Tower", "One WTC"], a: 0, cat: "Fun" },
  { q: "Burj Khalifa is in which country?", opts: ["Qatar", "UAE", "Saudi Arabia"], a: 1, cat: "Fun" },
  { q: "The Statue of Unity is a statue of:", opts: ["Nehru", "Sardar Patel", "Gandhi"], a: 1, cat: "Fun" },
  { q: "The Statue of Unity is in:", opts: ["Maharashtra", "Gujarat", "Rajasthan"], a: 1, cat: "Fun" },
  { q: "'Sherlock Holmes' was created by:", opts: ["Agatha Christie", "Arthur Conan Doyle", "Mark Twain"], a: 1, cat: "Fun" },
  { q: "What is the currency of India?", opts: ["Rupee", "Taka", "Rupiah"], a: 0, cat: "Fun" },
  { q: "The 'City of Joy' is:", opts: ["Mumbai", "Kolkata", "Delhi"], a: 1, cat: "Fun" },
  { q: "The 'Silicon Valley of India' is:", opts: ["Hyderabad", "Bengaluru", "Chennai"], a: 1, cat: "Fun" },
  { q: "The 'Pink City' of India is:", opts: ["Jaipur", "Udaipur", "Jodhpur"], a: 0, cat: "Fun" },
  { q: "The 'Blue City' of India is:", opts: ["Jaipur", "Jodhpur", "Udaipur"], a: 1, cat: "Fun" },
  { q: "The 'City of Lakes' is:", opts: ["Jodhpur", "Udaipur", "Jaipur"], a: 1, cat: "Fun" },
  { q: "West Bengal's capital is:", opts: ["Kolkata", "Howrah", "Darjeeling"], a: 0, cat: "Fun" },
  { q: "Barasat is in which state?", opts: ["Bihar", "West Bengal", "Odisha"], a: 1, cat: "Fun" },
];
