// Curated bank of words & thoughts. Used for instant shuffle (no API call needed).
export const WORDS: { word: string; meaning: string }[] = [
  { word: "Resilient", meaning: "Able to recover quickly from difficulties." },
  { word: "Tenacious", meaning: "Holding on firmly; never giving up easily." },
  { word: "Eloquent", meaning: "Speaking or writing in a clear, powerful way." },
  { word: "Diligent", meaning: "Showing care and steady effort in work." },
  { word: "Audacious", meaning: "Showing a willingness to take bold risks." },
  { word: "Benevolent", meaning: "Kind, generous and well-meaning." },
  { word: "Candid", meaning: "Truthful and straightforward in speech." },
  { word: "Compassionate", meaning: "Feeling and showing concern for others." },
  { word: "Curious", meaning: "Eager to learn or know more." },
  { word: "Empathy", meaning: "Understanding what another person feels." },
  { word: "Frugal", meaning: "Using money or resources carefully." },
  { word: "Genuine", meaning: "Real, honest and sincere." },
  { word: "Humble", meaning: "Modest about your own achievements." },
  { word: "Ingenious", meaning: "Clever, original and inventive." },
  { word: "Jubilant", meaning: "Feeling or showing great happiness." },
  { word: "Kindle", meaning: "To light up or arouse a feeling." },
  { word: "Luminous", meaning: "Full of light; shining brightly." },
  { word: "Meticulous", meaning: "Showing great attention to detail." },
  { word: "Novel", meaning: "New, fresh and original." },
  { word: "Optimistic", meaning: "Hopeful and confident about the future." },
  { word: "Prudent", meaning: "Careful and wise in making decisions." },
  { word: "Quaint", meaning: "Attractively unusual or old-fashioned." },
  { word: "Resolute", meaning: "Firm and determined in purpose." },
  { word: "Serene", meaning: "Calm, peaceful and untroubled." },
  { word: "Tranquil", meaning: "Free from disturbance; calm." },
  { word: "Unwavering", meaning: "Steady and not changing." },
  { word: "Vigilant", meaning: "Keeping careful watch for danger." },
  { word: "Wholesome", meaning: "Good for health and well-being." },
  { word: "Zealous", meaning: "Showing great energy for a cause." },
  { word: "Articulate", meaning: "Able to speak fluently and clearly." },
  { word: "Boisterous", meaning: "Noisy, energetic and cheerful." },
  { word: "Cordial", meaning: "Warm and friendly in manner." },
  { word: "Dynamic", meaning: "Full of energy and new ideas." },
  { word: "Earnest", meaning: "Serious and sincere in intention." },
  { word: "Fortitude", meaning: "Courage in pain or difficulty." },
  { word: "Gracious", meaning: "Kind, courteous and pleasant." },
  { word: "Harmonious", meaning: "Working together in a pleasing way." },
  { word: "Insightful", meaning: "Showing deep understanding." },
  { word: "Judicious", meaning: "Showing good judgment." },
  { word: "Keen", meaning: "Sharp, eager and enthusiastic." },
  { word: "Lucid", meaning: "Easy to understand; very clear." },
  { word: "Magnanimous", meaning: "Generous and forgiving, especially to a rival." },
  { word: "Nimble", meaning: "Quick and light in movement or thought." },
  { word: "Ornate", meaning: "Decorated in a fancy, detailed way." },
  { word: "Profound", meaning: "Very deep, thoughtful or important." },
  { word: "Quell", meaning: "To calm or put an end to something." },
  { word: "Radiant", meaning: "Sending out light; shining brightly." },
  { word: "Sagacious", meaning: "Having keen practical wisdom." },
  { word: "Tactful", meaning: "Careful not to upset or offend." },
  { word: "Ubiquitous", meaning: "Present, appearing or found everywhere." },
  { word: "Vivacious", meaning: "Full of life and energy." },
  { word: "Whimsical", meaning: "Playfully unusual and imaginative." },
  { word: "Yearn", meaning: "To long for something deeply." },
  { word: "Adept", meaning: "Very skilled at something." },
  { word: "Brisk", meaning: "Quick, active and energetic." },
  { word: "Cogent", meaning: "Clear, logical and convincing." },
  { word: "Devout", meaning: "Deeply committed or sincere." },
  { word: "Exemplary", meaning: "Serving as a perfect example." },
  { word: "Fervent", meaning: "Showing great warmth or intensity." },
  { word: "Gallant", meaning: "Brave, heroic and noble." },
];

export const THOUGHTS: { thought: string; author: string | null }[] = [
  { thought: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { thought: "It always seems impossible until it is done.", author: "Nelson Mandela" },
  { thought: "Education is the most powerful weapon you can use to change the world.", author: "Nelson Mandela" },
  { thought: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { thought: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { thought: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { thought: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { thought: "Don't watch the clock; do what it does — keep going.", author: "Sam Levenson" },
  { thought: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { thought: "Whether you think you can or you think you can't — you're right.", author: "Henry Ford" },
  { thought: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { thought: "We cannot solve our problems with the same thinking we used when we created them.", author: "Albert Einstein" },
  { thought: "Try not to become a person of success, but rather a person of value.", author: "Albert Einstein" },
  { thought: "Arise! Awake! And stop not till the goal is reached.", author: "Swami Vivekananda" },
  { thought: "You have to dream before your dreams can come true.", author: "A.P.J. Abdul Kalam" },
  { thought: "If you want to shine like a sun, first burn like a sun.", author: "A.P.J. Abdul Kalam" },
  { thought: "Don't take rest after your first victory because if you fail in second, more lips are waiting to say that your first victory was just luck.", author: "A.P.J. Abdul Kalam" },
  { thought: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
  { thought: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
  { thought: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { thought: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { thought: "A river cuts through rock not because of its power, but its persistence.", author: "James N. Watkins" },
  { thought: "Stars can't shine without darkness.", author: null },
  { thought: "Small daily improvements are the key to staggering long-term results.", author: null },
  { thought: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { thought: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { thought: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { thought: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
  { thought: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { thought: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { thought: "Wisdom begins in wonder.", author: "Socrates" },
  { thought: "The mind is everything. What you think you become.", author: "Buddha" },
  { thought: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry" },
  { thought: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { thought: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { thought: "Learning never exhausts the mind.", author: "Leonardo da Vinci" },
  { thought: "Either I will find a way, or I will make one.", author: "Philip Sidney" },
  { thought: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { thought: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { thought: "The best way to predict the future is to create it.", author: "Peter Drucker" },
];

// Deterministic but date+seed dependent picks.
export function pickFromBank(date: string, seed: number) {
  const hash = (s: string) => {
    let h = 2166136261;
    for (let i = 0; i < s.length; i++) {
      h = (h ^ s.charCodeAt(i)) >>> 0;
      h = Math.imul(h, 16777619) >>> 0;
    }
    return h;
  };
  const n = hash(date + ":" + seed);
  const w = WORDS[n % WORDS.length];
  const t = THOUGHTS[(n >>> 8) % THOUGHTS.length];
  return {
    word: w.word,
    word_meaning: w.meaning,
    thought: t.thought,
    thought_author: t.author,
  };
}
