// Curated bank of words & thoughts. Rotates daily.
export type WordEntry = { word: string; meaning: string; example: string };
export type ThoughtEntry = { thought: string; author: string | null };

export const WORDS: WordEntry[] = [
  { word: "Resilient", meaning: "Able to recover quickly from difficulties.", example: "She was resilient and bounced back after failing the test." },
  { word: "Tenacious", meaning: "Holding on firmly; never giving up easily.", example: "His tenacious effort finally won him the trophy." },
  { word: "Eloquent", meaning: "Speaking or writing in a clear, powerful way.", example: "Her eloquent speech moved the entire audience." },
  { word: "Diligent", meaning: "Showing care and steady effort in work.", example: "A diligent student finishes homework on time every day." },
  { word: "Audacious", meaning: "Showing a willingness to take bold risks.", example: "It was an audacious plan, but it worked perfectly." },
  { word: "Benevolent", meaning: "Kind, generous and well-meaning.", example: "Our principal is a benevolent leader who helps every student." },
  { word: "Candid", meaning: "Truthful and straightforward in speech.", example: "I appreciate your candid opinion about my project." },
  { word: "Compassionate", meaning: "Feeling and showing concern for others.", example: "The compassionate nurse comforted every patient." },
  { word: "Curious", meaning: "Eager to learn or know more.", example: "Curious children always ask the best questions." },
  { word: "Empathy", meaning: "Understanding what another person feels.", example: "Show empathy when your friend is having a bad day." },
  { word: "Frugal", meaning: "Using money or resources carefully.", example: "Being frugal helped him save enough for a new bike." },
  { word: "Genuine", meaning: "Real, honest and sincere.", example: "Her smile was warm and genuine." },
  { word: "Humble", meaning: "Modest about your own achievements.", example: "Even after winning, he remained humble." },
  { word: "Ingenious", meaning: "Clever, original and inventive.", example: "What an ingenious way to solve the puzzle!" },
  { word: "Jubilant", meaning: "Feeling or showing great happiness.", example: "The team was jubilant after winning the match." },
  { word: "Kindle", meaning: "To light up or arouse a feeling.", example: "A good teacher can kindle a love for learning." },
  { word: "Luminous", meaning: "Full of light; shining brightly.", example: "The luminous moon lit up the whole garden." },
  { word: "Meticulous", meaning: "Showing great attention to detail.", example: "She is meticulous about keeping her notebook tidy." },
  { word: "Novel", meaning: "New, fresh and original.", example: "He came up with a novel idea for the science fair." },
  { word: "Optimistic", meaning: "Hopeful and confident about the future.", example: "Stay optimistic — tomorrow is a new day." },
  { word: "Prudent", meaning: "Careful and wise in making decisions.", example: "A prudent student plans before each exam." },
  { word: "Quaint", meaning: "Attractively unusual or old-fashioned.", example: "We visited a quaint little village near the hills." },
  { word: "Resolute", meaning: "Firm and determined in purpose.", example: "She was resolute in her goal to become a doctor." },
  { word: "Serene", meaning: "Calm, peaceful and untroubled.", example: "The lake looked serene in the morning light." },
  { word: "Tranquil", meaning: "Free from disturbance; calm.", example: "The temple has a tranquil atmosphere." },
  { word: "Unwavering", meaning: "Steady and not changing.", example: "His unwavering support helped me through hard times." },
  { word: "Vigilant", meaning: "Keeping careful watch for danger.", example: "Be vigilant while crossing busy roads." },
  { word: "Wholesome", meaning: "Good for health and well-being.", example: "Fruits and vegetables make a wholesome meal." },
  { word: "Zealous", meaning: "Showing great energy for a cause.", example: "She is a zealous member of the eco club." },
  { word: "Articulate", meaning: "Able to speak fluently and clearly.", example: "He gave an articulate answer to every question." },
  { word: "Boisterous", meaning: "Noisy, energetic and cheerful.", example: "The boisterous crowd cheered for the home team." },
  { word: "Cordial", meaning: "Warm and friendly in manner.", example: "Our neighbours are very cordial and helpful." },
  { word: "Dynamic", meaning: "Full of energy and new ideas.", example: "She is a dynamic leader of the student council." },
  { word: "Earnest", meaning: "Serious and sincere in intention.", example: "His earnest effort impressed the judges." },
  { word: "Fortitude", meaning: "Courage in pain or difficulty.", example: "She showed great fortitude during her long illness." },
  { word: "Gracious", meaning: "Kind, courteous and pleasant.", example: "Thank you for being such a gracious host." },
  { word: "Harmonious", meaning: "Working together in a pleasing way.", example: "Our class is a harmonious group of friends." },
  { word: "Insightful", meaning: "Showing deep understanding.", example: "Her insightful comments helped the whole team." },
  { word: "Judicious", meaning: "Showing good judgment.", example: "Make a judicious choice about your career." },
  { word: "Keen", meaning: "Sharp, eager and enthusiastic.", example: "He has a keen interest in astronomy." },
  { word: "Lucid", meaning: "Easy to understand; very clear.", example: "The teacher gave a lucid explanation of fractions." },
  { word: "Magnanimous", meaning: "Generous and forgiving, especially to a rival.", example: "It was magnanimous of him to congratulate the winner." },
  { word: "Nimble", meaning: "Quick and light in movement or thought.", example: "A nimble mind solves problems quickly." },
  { word: "Ornate", meaning: "Decorated in a fancy, detailed way.", example: "The palace had ornate golden ceilings." },
  { word: "Profound", meaning: "Very deep, thoughtful or important.", example: "The book had a profound effect on my thinking." },
  { word: "Quell", meaning: "To calm or put an end to something.", example: "A glass of water helped quell my thirst." },
  { word: "Radiant", meaning: "Sending out light; shining brightly.", example: "Her face was radiant with joy." },
  { word: "Sagacious", meaning: "Having keen practical wisdom.", example: "We listened to the sagacious advice of our grandfather." },
  { word: "Tactful", meaning: "Careful not to upset or offend.", example: "Be tactful when telling someone bad news." },
  { word: "Ubiquitous", meaning: "Present, appearing or found everywhere.", example: "Smartphones are now ubiquitous in our school." },
  { word: "Vivacious", meaning: "Full of life and energy.", example: "Her vivacious personality lit up the classroom." },
  { word: "Whimsical", meaning: "Playfully unusual and imaginative.", example: "He made a whimsical drawing of a flying elephant." },
  { word: "Yearn", meaning: "To long for something deeply.", example: "I yearn to travel to the mountains again." },
  { word: "Adept", meaning: "Very skilled at something.", example: "She is adept at solving Rubik's cubes." },
  { word: "Brisk", meaning: "Quick, active and energetic.", example: "We went for a brisk walk in the park." },
  { word: "Cogent", meaning: "Clear, logical and convincing.", example: "He gave a cogent reason for being late." },
  { word: "Devout", meaning: "Deeply committed or sincere.", example: "She is a devout reader of mystery novels." },
  { word: "Exemplary", meaning: "Serving as a perfect example.", example: "Her exemplary behaviour earned her the badge." },
  { word: "Fervent", meaning: "Showing great warmth or intensity.", example: "He is a fervent supporter of our team." },
  { word: "Gallant", meaning: "Brave, heroic and noble.", example: "The gallant soldier saved many lives." },
  { word: "Astute", meaning: "Quick to understand a situation.", example: "An astute observer notices small details." },
  { word: "Bountiful", meaning: "Large in quantity; plentiful.", example: "We had a bountiful harvest this year." },
  { word: "Cherish", meaning: "To hold something dear; to value.", example: "I cherish every memory of my best friend." },
  { word: "Dazzle", meaning: "To impress greatly with brilliance.", example: "The fireworks dazzled the children." },
  { word: "Endure", meaning: "To bear with patience.", example: "He endured the long journey without complaint." },
  { word: "Flourish", meaning: "To grow well or be very successful.", example: "Plants flourish in good sunlight." },
  { word: "Gratitude", meaning: "Feeling of being thankful.", example: "Always express gratitude to your teachers." },
  { word: "Honor", meaning: "High respect or great esteem.", example: "It is an honor to lead the class." },
  { word: "Inspire", meaning: "To fill with the urge to do something.", example: "His story inspired me to study harder." },
  { word: "Joyful", meaning: "Feeling or expressing great pleasure.", example: "The classroom was joyful on the last day." },
  { word: "Kinship", meaning: "A sharing of characteristics; close connection.", example: "I feel a kinship with anyone who loves books." },
  { word: "Lively", meaning: "Full of life and energy.", example: "We had a lively discussion in class today." },
  { word: "Mindful", meaning: "Conscious and aware of something.", example: "Be mindful of your words." },
  { word: "Nurture", meaning: "To care for and encourage growth.", example: "Parents nurture their children with love." },
  { word: "Observant", meaning: "Quick to notice things.", example: "An observant detective sees every clue." },
  { word: "Persevere", meaning: "To continue despite difficulties.", example: "If you persevere, you will succeed." },
  { word: "Quench", meaning: "To satisfy thirst or a desire.", example: "Cold water can quench your thirst on a hot day." },
  { word: "Rejoice", meaning: "To feel or show great joy.", example: "We rejoiced when our team won the match." },
  { word: "Sincere", meaning: "Free from pretence; honest.", example: "Please accept my sincere apology." },
  { word: "Thrive", meaning: "To grow or develop well.", example: "Children thrive in a caring environment." },
  { word: "Uplift", meaning: "To raise spirits or improve.", example: "Good music can uplift your mood." },
  { word: "Valiant", meaning: "Showing courage or determination.", example: "The valiant firefighter rescued the kitten." },
  { word: "Wisdom", meaning: "The quality of having good judgment.", example: "With age comes wisdom." },
  { word: "Xenial", meaning: "Hospitable, especially to visitors.", example: "Our hosts were warm and xenial." },
  { word: "Yield", meaning: "To produce or give in.", example: "Hard work always yields good results." },
  { word: "Affable", meaning: "Friendly, good-natured and easy to talk to.", example: "Our new teacher is very affable." },
  { word: "Bliss", meaning: "Perfect happiness; great joy.", example: "A holiday with family is pure bliss." },
  { word: "Concise", meaning: "Giving information clearly in few words.", example: "Write a concise summary of the chapter." },
  { word: "Determined", meaning: "Having made a firm decision.", example: "She is determined to top her class." },
  { word: "Empower", meaning: "To give someone power or confidence.", example: "Education empowers young minds." },
  { word: "Fluent", meaning: "Able to speak smoothly and easily.", example: "He is fluent in three languages." },
  { word: "Grateful", meaning: "Showing appreciation for kindness.", example: "I am grateful for your help." },
  { word: "Hopeful", meaning: "Feeling or inspiring optimism.", example: "She is hopeful about the exam result." },
  { word: "Inquisitive", meaning: "Eager for knowledge.", example: "His inquisitive nature made him a great scientist." },
  { word: "Jovial", meaning: "Cheerful and friendly.", example: "Our jovial uncle always tells funny stories." },
  { word: "Knack", meaning: "A special skill or talent.", example: "She has a knack for drawing." },
  { word: "Loyal", meaning: "Faithful and dependable.", example: "A loyal friend is hard to find." },
  { word: "Modest", meaning: "Not boastful about abilities.", example: "Despite winning, he remained modest." },
  { word: "Noble", meaning: "Having fine personal qualities.", example: "Helping the poor is a noble act." },
  { word: "Outstanding", meaning: "Exceptionally good.", example: "She did an outstanding performance on stage." },
  { word: "Polite", meaning: "Showing good manners.", example: "Always be polite to elders." },
  { word: "Quick-witted", meaning: "Showing intelligence in a fast way.", example: "His quick-witted reply made everyone laugh." },
  { word: "Reliable", meaning: "Able to be trusted.", example: "He is a reliable team member." },
  { word: "Steadfast", meaning: "Firmly fixed in place; unwavering.", example: "She is steadfast in her beliefs." },
  { word: "Thoughtful", meaning: "Showing consideration for others.", example: "What a thoughtful birthday gift!" },
  { word: "Unique", meaning: "Being the only one of its kind.", example: "Every student has a unique talent." },
  { word: "Versatile", meaning: "Able to do many different things.", example: "She is a versatile player on the field." },
  { word: "Witty", meaning: "Clever and amusing in speech.", example: "His witty jokes keep us laughing." },
  { word: "Zest", meaning: "Great enthusiasm and energy.", example: "She lives life with so much zest." },
  { word: "Ambitious", meaning: "Having a strong desire for success.", example: "Be ambitious but also kind." },
  { word: "Brilliant", meaning: "Exceptionally clever or talented.", example: "That was a brilliant solution to the problem." },
  { word: "Creative", meaning: "Using imagination to make something new.", example: "Her creative project won first prize." },
  { word: "Disciplined", meaning: "Showing controlled behaviour.", example: "A disciplined athlete trains daily." },
  { word: "Effortless", meaning: "Done with ease.", example: "Her effortless dancing amazed us." },
  { word: "Focused", meaning: "Paying full attention.", example: "Stay focused during the exam." },
  { word: "Generous", meaning: "Willing to give and share freely.", example: "She is generous with her time and books." },
  { word: "Honest", meaning: "Truthful and trustworthy.", example: "Always be honest with your parents." },
  { word: "Intuitive", meaning: "Understanding without needing reasoning.", example: "She has an intuitive sense of music." },
  { word: "Joy", meaning: "A feeling of great pleasure.", example: "Helping others brings joy." },
  { word: "Kindhearted", meaning: "Caring and sympathetic.", example: "Our kindhearted teacher always listens." },
  { word: "Limitless", meaning: "Without end or bounds.", example: "Your imagination is limitless." },
  { word: "Motivated", meaning: "Eager to do something well.", example: "A motivated student never gives up." },
];

export const THOUGHTS: ThoughtEntry[] = [
  { thought: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { thought: "It always seems impossible until it is done.", author: "Nelson Mandela" },
  { thought: "Education is the most powerful weapon you can use to change the world.", author: "Nelson Mandela" },
  { thought: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { thought: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { thought: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { thought: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { thought: "Don't watch the clock; do what it does — keep going.", author: "Sam Levenson" },
  { thought: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { thought: "Whether you think you can or you think you can't — you're right.", author: "Henry Ford" },
  { thought: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { thought: "We cannot solve our problems with the same thinking we used when we created them.", author: "Albert Einstein" },
  { thought: "Try not to become a person of success, but rather a person of value.", author: "Albert Einstein" },
  { thought: "Arise! Awake! And stop not till the goal is reached.", author: "Swami Vivekananda" },
  { thought: "You have to dream before your dreams can come true.", author: "A.P.J. Abdul Kalam" },
  { thought: "If you want to shine like a sun, first burn like a sun.", author: "A.P.J. Abdul Kalam" },
  { thought: "Don't take rest after your first victory — more challenges await.", author: "A.P.J. Abdul Kalam" },
  { thought: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
  { thought: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
  { thought: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { thought: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { thought: "A river cuts through rock not because of its power, but its persistence.", author: "James N. Watkins" },
  { thought: "Stars can't shine without darkness.", author: null },
  { thought: "Small daily improvements are the key to staggering long-term results.", author: null },
  { thought: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { thought: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { thought: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { thought: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
  { thought: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { thought: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { thought: "Wisdom begins in wonder.", author: "Socrates" },
  { thought: "The mind is everything. What you think you become.", author: "Buddha" },
  { thought: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry" },
  { thought: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { thought: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { thought: "Learning never exhausts the mind.", author: "Leonardo da Vinci" },
  { thought: "Either I will find a way, or I will make one.", author: "Philip Sidney" },
  { thought: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { thought: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { thought: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { thought: "Push yourself, because no one else is going to do it for you.", author: null },
  { thought: "Great things never come from comfort zones.", author: null },
  { thought: "Dream it. Wish it. Do it.", author: null },
  { thought: "Success doesn't just find you. You have to go out and get it.", author: null },
  { thought: "Don't stop when you're tired. Stop when you're done.", author: null },
  { thought: "Wake up with determination. Go to bed with satisfaction.", author: null },
  { thought: "Do something today that your future self will thank you for.", author: null },
  { thought: "Little things make big days.", author: null },
  { thought: "It's going to be hard, but hard does not mean impossible.", author: null },
  { thought: "Don't wait for opportunity. Create it.", author: null },
  { thought: "Sometimes we're tested not to show our weaknesses, but to discover our strengths.", author: null },
  { thought: "The key to success is to focus on goals, not obstacles.", author: null },
  { thought: "Dream bigger. Do bigger.", author: null },
  { thought: "The harder you work for something, the greater you'll feel when you achieve it.", author: null },
  { thought: "Be so good they can't ignore you.", author: "Steve Martin" },
  { thought: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { thought: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { thought: "What we think, we become.", author: "Buddha" },
  { thought: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { thought: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison" },
  { thought: "Every accomplishment starts with the decision to try.", author: "John F. Kennedy" },
  { thought: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { thought: "Today's accomplishments were yesterday's impossibilities.", author: "Robert H. Schuller" },
  { thought: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { thought: "A winner is a dreamer who never gives up.", author: "Nelson Mandela" },
  { thought: "If you can dream it, you can do it.", author: "Walt Disney" },
  { thought: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { thought: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
  { thought: "Limit your 'always' and your 'nevers.'", author: "Amy Poehler" },
  { thought: "Either you run the day or the day runs you.", author: "Jim Rohn" },
  { thought: "Knowledge is power.", author: "Francis Bacon" },
  { thought: "The mind, once stretched by a new idea, never returns to its original dimensions.", author: "Ralph Waldo Emerson" },
  { thought: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { thought: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { thought: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { thought: "A smooth sea never made a skilled sailor.", author: "Franklin D. Roosevelt" },
  { thought: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
  { thought: "Courage doesn't always roar; sometimes it's the quiet voice saying 'I will try again tomorrow.'", author: "Mary Anne Radmacher" },
  { thought: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { thought: "Setting goals is the first step in turning the invisible into the visible.", author: "Tony Robbins" },
  { thought: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
];

// Deterministic but date+seed dependent picks.
export function pickFromBank(date: string, seed: number) {
  const hash = (s: string) => {
    let h = 2166136261;
    for (let i = 0; i < s.length; i++) {
      h = (h ^ s.charCodeAt(i)) >>> 0;
      h = Math.imul(h, 16777619) >>> 0;
    }
    return h;
  };
  const n = hash(date + ":" + seed);
  const w = WORDS[n % WORDS.length];
  const t = THOUGHTS[(n >>> 8) % THOUGHTS.length];
  return {
    word: w.word,
    word_meaning: w.meaning,
    word_example: w.example,
    thought: t.thought,
    thought_author: t.author,
  };
}

// Today's auto pick — rotates daily based on date.
export function pickForDate(date: string) {
  return pickFromBank(date, 0);
}
