/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VawsumRouteImport } from './routes/vawsum'
import { Route as RoutineRouteImport } from './routes/routine'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as HomeworkRouteImport } from './routes/homework'
import { Route as HolidaysRouteImport } from './routes/holidays'
import { Route as FunzoneRouteImport } from './routes/funzone'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BirthdaysRouteImport } from './routes/birthdays'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as IndexRouteImport } from './routes/index'

const VawsumRoute = VawsumRouteImport.update({
  id: '/vawsum',
  path: '/vawsum',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineRoute = RoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeworkRoute = HomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysRoute = HolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const FunzoneRoute = FunzoneRouteImport.update({
  id: '/funzone',
  path: '/funzone',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthdaysRoute = BirthdaysRouteImport.update({
  id: '/birthdays',
  path: '/birthdays',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/assistant': typeof AssistantRoute
  '/birthdays': typeof BirthdaysRoute
  '/chat': typeof ChatRoute
  '/daily': typeof DailyRoute
  '/downloads': typeof DownloadsRoute
  '/events': typeof EventsRoute
  '/funzone': typeof FunzoneRoute
  '/holidays': typeof HolidaysRoute
  '/homework': typeof HomeworkRoute
  '/memories': typeof MemoriesRoute
  '/notes': typeof NotesRoute
  '/routine': typeof RoutineRoute
  '/vawsum': typeof VawsumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/assistant': typeof AssistantRoute
  '/birthdays': typeof BirthdaysRoute
  '/chat': typeof ChatRoute
  '/daily': typeof DailyRoute
  '/downloads': typeof DownloadsRoute
  '/events': typeof EventsRoute
  '/funzone': typeof FunzoneRoute
  '/holidays': typeof HolidaysRoute
  '/homework': typeof HomeworkRoute
  '/memories': typeof MemoriesRoute
  '/notes': typeof NotesRoute
  '/routine': typeof RoutineRoute
  '/vawsum': typeof VawsumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/assistant': typeof AssistantRoute
  '/birthdays': typeof BirthdaysRoute
  '/chat': typeof ChatRoute
  '/daily': typeof DailyRoute
  '/downloads': typeof DownloadsRoute
  '/events': typeof EventsRoute
  '/funzone': typeof FunzoneRoute
  '/holidays': typeof HolidaysRoute
  '/homework': typeof HomeworkRoute
  '/memories': typeof MemoriesRoute
  '/notes': typeof NotesRoute
  '/routine': typeof RoutineRoute
  '/vawsum': typeof VawsumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/assistant'
    | '/birthdays'
    | '/chat'
    | '/daily'
    | '/downloads'
    | '/events'
    | '/funzone'
    | '/holidays'
    | '/homework'
    | '/memories'
    | '/notes'
    | '/routine'
    | '/vawsum'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/assistant'
    | '/birthdays'
    | '/chat'
    | '/daily'
    | '/downloads'
    | '/events'
    | '/funzone'
    | '/holidays'
    | '/homework'
    | '/memories'
    | '/notes'
    | '/routine'
    | '/vawsum'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/assistant'
    | '/birthdays'
    | '/chat'
    | '/daily'
    | '/downloads'
    | '/events'
    | '/funzone'
    | '/holidays'
    | '/homework'
    | '/memories'
    | '/notes'
    | '/routine'
    | '/vawsum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AssistantRoute: typeof AssistantRoute
  BirthdaysRoute: typeof BirthdaysRoute
  ChatRoute: typeof ChatRoute
  DailyRoute: typeof DailyRoute
  DownloadsRoute: typeof DownloadsRoute
  EventsRoute: typeof EventsRoute
  FunzoneRoute: typeof FunzoneRoute
  HolidaysRoute: typeof HolidaysRoute
  HomeworkRoute: typeof HomeworkRoute
  MemoriesRoute: typeof MemoriesRoute
  NotesRoute: typeof NotesRoute
  RoutineRoute: typeof RoutineRoute
  VawsumRoute: typeof VawsumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vawsum': {
      id: '/vawsum'
      path: '/vawsum'
      fullPath: '/vawsum'
      preLoaderRoute: typeof VawsumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine': {
      id: '/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof RoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homework': {
      id: '/homework'
      path: '/homework'
      fullPath: '/homework'
      preLoaderRoute: typeof HomeworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays': {
      id: '/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof HolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funzone': {
      id: '/funzone'
      path: '/funzone'
      fullPath: '/funzone'
      preLoaderRoute: typeof FunzoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birthdays': {
      id: '/birthdays'
      path: '/birthdays'
      fullPath: '/birthdays'
      preLoaderRoute: typeof BirthdaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AssistantRoute: AssistantRoute,
  BirthdaysRoute: BirthdaysRoute,
  ChatRoute: ChatRoute,
  DailyRoute: DailyRoute,
  DownloadsRoute: DownloadsRoute,
  EventsRoute: EventsRoute,
  FunzoneRoute: FunzoneRoute,
  HolidaysRoute: HolidaysRoute,
  HomeworkRoute: HomeworkRoute,
  MemoriesRoute: MemoriesRoute,
  NotesRoute: NotesRoute,
  RoutineRoute: RoutineRoute,
  VawsumRoute: VawsumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
